# 经验 金币倍率
world.exp=300
world.meso=1

# ++
world.startMap=993028000
world.warpMap=910000000
#true启用独立连接器 false：直接由主服务器处理网络连接，适合小型或测试环境。
world.useConnecter=true

# 是否僅限管理員
world.admin=false

# 1=禁用PQ 0=啟用PQ
world.flags=0

# 伺服器名稱
login.serverName= KMS 391

# 頻道選擇時的事件消息
login.eventMessage=

# 設定服務器UI
login.serverUI=UI/UIWindow6.img/loginNoticePopup/sundayMaple_181111


# false：直接跳转地图，无额外视觉效果（提升性能）。 # true：启用地图切换的专属UI效果（增强沉浸感）。
login.ChangeMapUI=true

# 頻道選擇標記 0：無 1：事件 2：新 3：熱門
login.flag=0

# 每個帳戶的初始字元數
login.maxCharacters=40

# 服務器滾動消息
world.serverMessage=Maplestory,download from our website www.wydjg.cn

# 服務器的總用戶限制
login.userlimit=1500

# 客户端切图/进频道时使用的网关IP（必须是外部客户端可达IPv4）
world.gateway.ip=127.0.0.1
# 本地模式开关（影响isLocalhost判断）
world.useLocalhost=false

# 通道服務器的默認設置
channel.net.port=5455
channel.net.interface=127.0.0.1

# 活動事件腳本
channel.events=Easy_Magnus,Hard_Dunkel,Chaos_Dusk,Easy_Lucid,Hard_Seren,Easy_Cygnus,Easy_Arkarium,Easy_Populatus,Extreme_Lotus,Extreme_Demian,Extreme_Lucid,Extreme_Will,GuildBoss,Muto,Black_Mage,Normal_JinHillah,Normal_Dunkel,Normal_Dusk,Savior,DreamBreaker,AdventureDrill,Normal_Zakum,Chaos_Zakum,Normal_Magnus,Hard_Magnus,Normal_Hillah,Hard_Hillah,Normal_Kawoong,Normal_Populatus,Chaos_Populatus,Normal_Pierre,Chaos_Pierre,Normal_VonBon,Chaos_VonBon,Normal_BloodyQueen,Chaos_BloodyQueen,Normal_Vellum,Chaos_Vellum,Normal_VonLeon,Hard_VonLeon,Normal_Cygnus,Normal_Pinkbean,Chaos_Pinkbean,Normal_Horntail,Chaos_Horntail,Normal_Arkarium,Normal_Lotus,Hard_Lotus,Normal_Demian,Hard_Demian,Normal_Lucid,Hard_Lucid,Dorothy,Balrog,Normal_Will,Hard_Will,test1,test2,test3,CrystalChallenge,Extreme_JinHillah,Extreme_Seren,Extreme_Dusk,Extreme_Dunkel,Extreme_Black_Mage,Hell_JinHillah,Hell_Dunkel,Hell_Dusk,Hell_Black_Mage,Hell_Seren,WorldBoss,max_Karlos,Chaos_Karlos,Normal_GES,Chaos_Mitsuhide,Jgg,Teng,MoonPQ,RP_PQ,KerningPQ,PoisonForest,moonpig,EscapePQ,Chaos_Karing,Extreme_Karlos,rnjPQ,DamageMeter

# 事件發生率
world.eventBonus = 0
world.weddingBonus = 0
world.partyBonus = 0
world.pcBonus = 0
world.rainbowBonus = 0
world.boomBonus = 0
world.portionBonus = 0
world.restBonus = 0
world.itemBonus = 0
world.valueBonus = 0
world.iceBonus = 0
world.hpLiskBonus = 0
world.fieldBonus = 0
world.eventBonus2 = 0
world.fieldBonus2 = 0
